import Foundation
import PDFKit
import UIKit
import HealthKit
import SwiftData
import WakemeShared

@MainActor
final class ExportManager {

    enum Range: String, CaseIterable, Identifiable {
        case days30 = "30 days"
        case days90 = "90 days"
        case all    = "All time"
        var id: String { rawValue }

        var interval: DateInterval {
            let end = Date()
            switch self {
            case .days30: return DateInterval(start: Calendar.current.date(byAdding: .day, value: -30, to: end)!, end: end)
            case .days90: return DateInterval(start: Calendar.current.date(byAdding: .day, value: -90, to: end)!, end: end)
            case .all:    return DateInterval(start: .distantPast, end: end)
            }
        }
    }

    private let pageSize = CGRect(x: 0, y: 0, width: 612, height: 792)   // US Letter, 72 dpi
    private let footer   = "Generated by Wakeme. For reference only. Not a medical diagnosis."

    // MARK: - CSV

    func generateCSV(events: [SleepAttackEvent]) -> URL {
        var rows = [
            "timestamp,duration_seconds,severity,confidence,dismiss_type,was_reclassified," +
            "monitoring_mode,activity_context,heart_rate,hrv,hr_trend,hrv_trend,accel_trend,model_version"
        ]
        let iso = ISO8601DateFormatter()
        for e in events {
            let s = e.signalSnapshot
            let cols: [String] = [
                iso.string(from: e.timestamp),
                String(format: "%.0f", e.duration),
                "\(e.severity)",
                String(format: "%.3f", e.confidence),
                e.dismissType.rawValue,
                "\(e.wasReclassified)",
                e.monitoringMode.rawValue,
                e.activityContext.rawValue,
                s.map { String(format: "%.1f", $0.heartRate)    } ?? "",
                s.map { String(format: "%.1f", $0.hrv)          } ?? "",
                s.map { String(format: "%.2f", $0.hrTrend)      } ?? "",
                s.map { String(format: "%.2f", $0.hrvTrend)     } ?? "",
                s.map { String(format: "%.3f", $0.accelTrend)   } ?? "",
                "\(e.modelVersion)"
            ]
            rows.append(cols.joined(separator: ","))
        }
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("wakeme_export_\(Int(Date().timeIntervalSince1970)).csv")
        try? rows.joined(separator: "\n").write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - PDF

    func generatePDF(events: [SleepAttackEvent],
                     falseNegatives: [FalseNegativeReport],
                     range: Range) async -> URL {
        let renderer = UIGraphicsPDFRenderer(bounds: pageSize)
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("wakeme_report_\(Int(Date().timeIntervalSince1970)).pdf")

        // Pre-fetch HR context before the synchronous render loop (capped at 12 to bound query time).
        let confirmed = events.filter { $0.dismissType == .confirmedAttack }
        let hrContexts = await fetchHRContexts(for: Array(confirmed.prefix(12)))

        try? renderer.writePDF(to: url) { ctx in
            drawSummaryPage(ctx, events: events, falseNegatives: falseNegatives, range: range,
                            confirmedShown: min(confirmed.count, 12))
            drawTimelinePage(ctx, events: events)
            drawHRContextPages(ctx, contexts: hrContexts)
        }
        return url
    }

    // MARK: - Summary page

    private func drawSummaryPage(_ ctx: UIGraphicsPDFRendererContext,
                                 events: [SleepAttackEvent],
                                 falseNegatives: [FalseNegativeReport],
                                 range: Range,
                                 confirmedShown: Int) {
        ctx.beginPage()
        var y: CGFloat = 48
        let confirmed  = events.filter { $0.dismissType == .confirmedAttack }.count
        let falseAlarms = events.filter { $0.dismissType == .falseAlarm }.count
        let total  = events.count
        let missed = falseNegatives.count
        let known  = confirmed + missed
        let recall    = known  == 0 ? 0 : Int(Double(confirmed)  / Double(known)  * 100)
        let falseRate = total  == 0 ? 0 : Int(Double(falseAlarms) / Double(total) * 100)

        y = drawText("Wakeme — Sleep Event Report", at: y, size: 22, bold: true)
        y = drawText("Range: \(range.rawValue)   Generated: \(Date().formatted(date: .abbreviated, time: .shortened))",
                     at: y + 4, size: 11, color: .gray)
        y += 16

        let rows: [(String, String)] = [
            ("Total events",           "\(total)"),
            ("Confirmed attacks",      "\(confirmed)"),
            ("False alarm rate",       "\(falseRate)%"),
            ("Detection recall",       known == 0 ? "—" : "\(recall)% (\(confirmed)/\(known))"),
            ("Most common hour",       mostCommonHour(events).map { "\($0):00" } ?? "—"),
            ("Missed (self-reported)", "\(missed)")
        ]
        for (label, value) in rows { y = drawKeyValue(label, value, at: y) }

        if confirmedShown < confirmed {
            y += 8
            y = drawText("HR context pages show the first 12 of \(confirmed) confirmed events.",
                         at: y, size: 9, color: .gray)
        }
        drawFooter(ctx)
    }

    private func mostCommonHour(_ events: [SleepAttackEvent]) -> Int? {
        let confirmed = events.filter { $0.dismissType == .confirmedAttack }
        guard !confirmed.isEmpty else { return nil }
        var counts: [Int: Int] = [:]
        for e in confirmed {
            counts[Calendar.current.component(.hour, from: e.timestamp), default: 0] += 1
        }
        return counts.max(by: { $0.value < $1.value })?.key
    }

    // MARK: - Timeline page

    private func drawTimelinePage(_ ctx: UIGraphicsPDFRendererContext,
                                   events: [SleepAttackEvent]) {
        ctx.beginPage()
        var y = drawText("Event timeline", at: 48, size: 18, bold: true)
        y += 12

        let cal        = Calendar.current
        let grouped    = Dictionary(grouping: events) { cal.startOfDay(for: $0.timestamp) }
        let days       = grouped.keys.sorted(by: >)
        let leftMargin: CGFloat = 100
        let rowWidth:   CGFloat = pageSize.width - leftMargin - 48
        let rowHeight:  CGFloat = 22

        for day in days.prefix(28) {
            drawText(day.formatted(.dateTime.month().day()), at: y, x: 48, size: 10)
            let cg = UIGraphicsGetCurrentContext()!
            cg.setStrokeColor(UIColor.systemGray5.cgColor)
            cg.setLineWidth(0.5)
            cg.move(to: CGPoint(x: leftMargin, y: y + rowHeight / 2))
            cg.addLine(to: CGPoint(x: leftMargin + rowWidth, y: y + rowHeight / 2))
            cg.strokePath()
            for e in grouped[day] ?? [] {
                let hour  = CGFloat(cal.component(.hour, from: e.timestamp))
                let x     = leftMargin + (hour / 24.0) * rowWidth
                let color: UIColor = e.dismissType == .confirmedAttack ? .systemRed
                    : (e.dismissType == .falseAlarm ? .systemGray : .systemOrange)
                cg.setFillColor(color.cgColor)
                cg.fill(CGRect(x: x - 1.5, y: y + 2, width: 3, height: rowHeight - 4))
            }
            y += rowHeight + 4
            if y > pageSize.height - 80 { drawFooter(ctx); ctx.beginPage(); y = 48 }
        }
        drawFooter(ctx)
    }

    // MARK: - HR context pages

    private struct HRContext {
        let event: SleepAttackEvent
        let samples: [(Date, Double)]
    }

    private func fetchHRContexts(for events: [SleepAttackEvent]) async -> [HRContext] {
        guard HKHealthStore.isHealthDataAvailable() else { return [] }
        let store = HKHealthStore()
        var out: [HRContext] = []
        for e in events {
            let start = e.timestamp.addingTimeInterval(-300)
            let end   = e.timestamp.addingTimeInterval(300)
            let pred  = HKQuery.predicateForSamples(withStart: start, end: end)
            let samples: [HKQuantitySample] = await withCheckedContinuation { cont in
                let q = HKSampleQuery(
                    sampleType: HKQuantityType(.heartRate),
                    predicate: pred,
                    limit: HKObjectQueryNoLimit,
                    sortDescriptors: [NSSortDescriptor(key: HKSampleSortIdentifierStartDate, ascending: true)]
                ) { _, s, _ in
                    cont.resume(returning: (s as? [HKQuantitySample]) ?? [])
                }
                store.execute(q)
            }
            let unit = HKUnit(from: "count/min")
            let pts  = samples.map { ($0.startDate, $0.quantity.doubleValue(for: unit)) }
            out.append(HRContext(event: e, samples: pts))
        }
        return out
    }

    private func drawHRContextPages(_ ctx: UIGraphicsPDFRendererContext, contexts: [HRContext]) {
        guard !contexts.isEmpty else { return }
        ctx.beginPage()
        var y = drawText("Heart rate around confirmed events (±5 min)", at: 48, size: 16, bold: true)
        y += 16
        for c in contexts {
            if y > pageSize.height - 160 { drawFooter(ctx); ctx.beginPage(); y = 48 }
            y = drawText(c.event.timestamp.formatted(date: .abbreviated, time: .shortened),
                         at: y, x: 48, size: 11, bold: true)
            drawMiniHRChart(c.samples, at: y, height: 90)
            y += 100
        }
        drawFooter(ctx)
    }

    private func drawMiniHRChart(_ samples: [(Date, Double)], at y: CGFloat, height: CGFloat) {
        guard samples.count > 1 else {
            drawText("No HR samples in window.", at: y, x: 60, size: 10, color: .gray); return
        }
        let cg     = UIGraphicsGetCurrentContext()!
        let left: CGFloat = 60, right = pageSize.width - 48
        let w      = right - left
        let hrs    = samples.map { $0.1 }
        let minHR  = (hrs.min() ?? 40) - 5
        let maxHR  = (hrs.max() ?? 100) + 5
        let times  = samples.map { $0.0.timeIntervalSince1970 }
        let t0 = times.first!, t1 = times.last!

        func px(_ t: Double) -> CGFloat { left + CGFloat((t - t0) / max(t1 - t0, 1)) * w }
        func py(_ hr: Double) -> CGFloat { y + height - CGFloat((hr - minHR) / max(maxHR - minHR, 1)) * height }

        cg.setStrokeColor(UIColor.systemRed.cgColor); cg.setLineWidth(1.5)
        cg.move(to: CGPoint(x: px(times[0]), y: py(hrs[0])))
        for i in 1..<samples.count { cg.addLine(to: CGPoint(x: px(times[i]), y: py(hrs[i]))) }
        cg.strokePath()
        drawText("\(Int(minHR))–\(Int(maxHR)) bpm", at: y, x: right - 70, size: 8, color: .gray)
    }

    // MARK: - Drawing helpers

    @discardableResult
    private func drawText(_ s: String, at y: CGFloat, x: CGFloat = 48, size: CGFloat = 12,
                          bold: Bool = false, color: UIColor = .black) -> CGFloat {
        let font = bold ? UIFont.boldSystemFont(ofSize: size) : UIFont.systemFont(ofSize: size)
        (s as NSString).draw(at: CGPoint(x: x, y: y),
                             withAttributes: [.font: font, .foregroundColor: color])
        return y + size + 6
    }

    @discardableResult
    private func drawKeyValue(_ k: String, _ v: String, at y: CGFloat) -> CGFloat {
        (k as NSString).draw(at: CGPoint(x: 48, y: y),
            withAttributes: [.font: UIFont.systemFont(ofSize: 12), .foregroundColor: UIColor.darkGray])
        (v as NSString).draw(at: CGPoint(x: 300, y: y),
            withAttributes: [.font: UIFont.boldSystemFont(ofSize: 12), .foregroundColor: UIColor.black])
        return y + 22
    }

    private func drawFooter(_ ctx: UIGraphicsPDFRendererContext) {
        (footer as NSString).draw(
            at: CGPoint(x: 48, y: pageSize.height - 36),
            withAttributes: [.font: UIFont.systemFont(ofSize: 8), .foregroundColor: UIColor.gray]
        )
    }
}
